spring:
  jackson:
    serialization-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
  
