server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iframework.demodb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: zhj777
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
