spring:
  jackson:
    serialization-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
security:
  jwt:
    token:
      secret-key: demoKey
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false


  
