server:
    port: 8082

security:
    oauth2:
        client:
            clientId: SpringBootMvc
            clientSecret: secret
            accessTokenUri: http://zero.teamcore.cn/ids/connect/token
            userAuthorizationUri: http://zero.teamcore.cn/ids/connect/authorize
            scope:
                - roles
                - profile
                - openid
            grant-type: authorization_code
        resource:
            userInfoUri: http://zero.teamcore.cn/ids/connect/userinfo